# Generated by Django 5.0.3 on 2024-03-12 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationalLearningInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=20)),
                ('number_of_generations', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='GenerationalLearningInstanceEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obsticals', models.JSONField()),
                ('goals', models.JSONField()),
                ('start', models.JSONField()),
                ('environment_size', models.JSONField()),
                ('relation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instance_environment', to='DataBase.generationallearninginstance')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_id', models.CharField(max_length=30)),
                ('number_of_agents', models.CharField(max_length=100)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_instance', to='DataBase.generationallearninginstance')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationAlpah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=20)),
                ('agent_fitness', models.CharField(max_length=100)),
                ('fitnessByStep', models.JSONField()),
                ('agentPath', models.JSONField()),
                ('relation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation_alpha', to='DataBase.generationinstance')),
            ],
        ),
        migrations.CreateModel(
            name='AgentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=20)),
                ('agent_fitness', models.CharField(max_length=100)),
                ('agent_path', models.JSONField()),
                ('agent_fitness_by_step', models.JSONField()),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_instance', to='DataBase.generationinstance')),
            ],
        ),
        migrations.CreateModel(
            name='InstanceAlpha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=20)),
                ('agent_fitness', models.CharField(max_length=100)),
                ('agent_path', models.JSONField()),
                ('agent_fitness_by_step', models.JSONField()),
                ('relation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instance_alpha', to='DataBase.generationallearninginstance')),
            ],
        ),
    ]
