# Generated by Django 5.0.3 on 2024-03-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0003_generationallearninginstancedatabasemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationallearninginstancedatabasemodel',
            name='number_of_generations',
            field=models.IntegerField(),
        ),
    ]
