# Generated by Django 5.0.3 on 2024-03-15 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0004_alter_generationallearninginstancedatabasemodel_number_of_generations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentInstance',
            new_name='AgentInstanceDataBaseModel',
        ),
        migrations.RenameModel(
            old_name='GenerationalLearningInstanceEnvironment',
            new_name='GenerationalLearningInstanceEnvironmentDataBaseModel',
        ),
        migrations.RenameModel(
            old_name='GenerationAlpah',
            new_name='GenerationAlpahDataBaseModel',
        ),
        migrations.RenameModel(
            old_name='GenerationInstance',
            new_name='GenerationInstanceDataBaseModel',
        ),
        migrations.RenameModel(
            old_name='InstanceAlpha',
            new_name='InstanceAlphaDataBaseModel',
        ),
    ]
