# Generated by Django 5.0.3 on 2024-03-20 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataBase", "0006_alter_generationinstancedatabasemodel_number_of_agents"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generationalpahdatabasemodel",
            name="relation",
        ),
        migrations.RemoveField(
            model_name="instancealphadatabasemodel",
            name="relation",
        ),
        migrations.CreateModel(
            name="BrainInstanceDataBaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brain_id", models.CharField(max_length=20)),
                ("brain_fitness", models.CharField(max_length=100)),
                ("brain_path", models.JSONField()),
                ("brain_fitness_by_step", models.JSONField()),
                ("brain_hidden_weights", models.JSONField()),
                ("brain_output_weights", models.JSONField()),
                (
                    "relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brain_instance",
                        to="DataBase.generationinstancedatabasemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GenerationAlpahBrainDataBaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brain_id", models.CharField(max_length=20)),
                ("brain_fitness", models.CharField(max_length=100)),
                ("brain_fitness_by_step", models.JSONField()),
                ("brain_Path", models.JSONField()),
                ("brain_hidden_weights", models.JSONField()),
                ("brain_output_weights", models.JSONField()),
                (
                    "relation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_alpha",
                        to="DataBase.generationinstancedatabasemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstanceAlphaBrainDataBaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brain_id", models.CharField(max_length=20)),
                ("brain_fitness", models.CharField(max_length=100)),
                ("brain_fitness_by_step", models.JSONField()),
                ("brain_Path", models.JSONField()),
                ("brain_hidden_weights", models.JSONField()),
                ("brain_output_weights", models.JSONField()),
                (
                    "relation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instance_alpha",
                        to="DataBase.generationallearninginstancedatabasemodel",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AgentInstanceDataBaseModel",
        ),
        migrations.DeleteModel(
            name="GenerationAlpahDataBaseModel",
        ),
        migrations.DeleteModel(
            name="InstanceAlphaDataBaseModel",
        ),
    ]
