# Generated by Django 5.0.3 on 2024-03-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataBase", "0007_remove_generationalpahdatabasemodel_relation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="braininstancedatabasemodel",
            name="brain_id",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="generationallearninginstancedatabasemodel",
            name="instance_id",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="generationalpahbraindatabasemodel",
            name="brain_id",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="generationinstancedatabasemodel",
            name="generation_id",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="instancealphabraindatabasemodel",
            name="brain_id",
            field=models.CharField(max_length=200),
        ),
    ]
