# Generated by Django 5.0.3 on 2024-03-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataBase", "0008_alter_braininstancedatabasemodel_brain_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="generationallearninginstanceenvironmentdatabasemodel",
            old_name="environment_size",
            new_name="environment_map",
        ),
        migrations.RenameField(
            model_name="generationallearninginstanceenvironmentdatabasemodel",
            old_name="goals",
            new_name="environment_map_dimensions",
        ),
        migrations.RenameField(
            model_name="generationallearninginstanceenvironmentdatabasemodel",
            old_name="obsticals",
            new_name="environment_start_coordinates",
        ),
        migrations.RemoveField(
            model_name="generationallearninginstanceenvironmentdatabasemodel",
            name="start",
        ),
        migrations.AddField(
            model_name="generationallearninginstanceenvironmentdatabasemodel",
            name="environment_maximum_action_count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
