# Generated by Django 5.0.3 on 2024-03-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "DataBase",
            "0009_rename_environment_size_generationallearninginstanceenvironmentdatabasemodel_environment_map_and_mor",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationallearninginstanceenvironmentdatabasemodel",
            name="environment_maximum_action_count",
            field=models.IntegerField(default=0),
        ),
    ]
