# Generated by Django 5.0.3 on 2024-03-21 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "DataBase",
            "0010_alter_generationallearninginstanceenvironmentdatabasemodel_environment_maximum_action_count",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="generationalpahbraindatabasemodel",
            old_name="brain_Path",
            new_name="brain_path",
        ),
        migrations.RenameField(
            model_name="instancealphabraindatabasemodel",
            old_name="brain_Path",
            new_name="brain_path",
        ),
    ]
