# Generated by Django 5.0.3 on 2024-03-26 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "DataBase",
            "0011_rename_brain_path_generationalpahbraindatabasemodel_brain_path_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="generationallearninginstancedatabasemodel",
            old_name="number_of_generations",
            new_name="number_of_sucessful_generations",
        ),
    ]
