# Generated by Django 5.0.3 on 2024-05-07 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "DataBase",
            "0014_generationallearninginstancedatabasemodel_generation_average_fitness_results",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="instancealphabraindatabasemodel",
            old_name="relation",
            new_name="instance_relation",
        ),
        migrations.AddField(
            model_name="generationalpahbraindatabasemodel",
            name="instance_relation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instance_relation",
                to="DataBase.generationallearninginstancedatabasemodel",
            ),
        ),
    ]
