# Generated by Django 5.0.3 on 2024-05-07 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "DataBase",
            "0015_rename_relation_instancealphabraindatabasemodel_instance_relation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationalpahbraindatabasemodel",
            name="instance_relation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alpha_instance",
                to="DataBase.generationallearninginstancedatabasemodel",
            ),
        ),
    ]
