# Generated by Django 5.0.3 on 2024-05-07 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataBase", "0016_alter_generationalpahbraindatabasemodel_instance_relation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instancealphabraindatabasemodel",
            name="instance_relation",
        ),
        migrations.CreateModel(
            name="AlphaBrainInstanceDataBaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brain_id", models.CharField(max_length=200)),
                ("brain_fitness", models.CharField(max_length=100)),
                ("brain_path", models.JSONField()),
                ("brain_fitness_by_step", models.JSONField()),
                ("brain_hidden_weights", models.JSONField()),
                ("brain_output_weights", models.JSONField()),
                (
                    "generation_relation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_relation",
                        to="DataBase.generationinstancedatabasemodel",
                    ),
                ),
                (
                    "instance_relation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instance_relation",
                        to="DataBase.generationinstancedatabasemodel",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="GenerationAlpahBrainDataBaseModel",
        ),
        migrations.DeleteModel(
            name="InstanceAlphaBrainDataBaseModel",
        ),
    ]
