# Generated by Django 5.0.3 on 2024-05-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataBase", "0018_alter_alphabraininstancedatabasemodel_instance_relation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationallearninginstanceenvironmentdatabasemodel",
            name="environment_map_dimensions",
            field=models.IntegerField(default=0),
        ),
    ]
